import { Button, Grid, Paper, TextField } from "@mui/material";
import { Inter } from "@next/font/google";
import Head from "next/head";
import Link from "next/link";
import { toast } from "react-toastify";
import { EnvModal, openEnvModal } from "../components/EnvModal";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex-1 flex flex-col p-4 ">
        <Paper className="w-4/5 mx-auto h-20 mb-12 flex justify-between px-4">
          <div className="flex items-center">
            <Link href="/management">
              <Button variant="contained" className="text-yellow-500">
                Management page
              </Button>
            </Link>
          </div>
          <div className="flex items-center">
            <Button
              variant="contained"
              className="text-yellow-500 h-min"
              onClick={() => {
                openEnvModal({
                  title: "Global environment",
                  onChange: (value) => {
                    toast("Global environment changed to " + value);
                  },
                  onCancel: () => {
                    toast("Global environment cancelled");
                  },
                  onSave: () => {
                    toast("Global environment saved");
                  },
                });
              }}
            >
              Global environment
            </Button>
          </div>
          <div className="flex gap-2 items-center py-6 ">
            <TextField type="text" label="App name" size="small" />
            <Button variant="contained" className="text-yellow-500">
              Add
            </Button>
          </div>
        </Paper>
        <div className="w-4/5 mx-auto">
          <Grid container spacing={2}>
            <Grid xs={3} item>
              <SignleAppPreview />
            </Grid>
            <Grid xs={3} item>
              <SignleAppPreview />
            </Grid>
            <Grid xs={3} item>
              <SignleAppPreview />
            </Grid>
            <Grid xs={3} item>
              <SignleAppPreview />
            </Grid>
            <Grid xs={3} item>
              <SignleAppPreview />
            </Grid>
            <Grid xs={3} item>
              <SignleAppPreview />
            </Grid>
          </Grid>
        </div>
      </main>
      <EnvModal />
    </>
  );
}

const SignleAppPreview = () => {
  return (
    <Paper className="p-4 h-[230px] flex flex-col">
      <h1 className="text-xl">RandomApp</h1>

      <div className="flex flex-col flex-1 my-4">
        <div>
          Status: <span className="text-green-500">Building</span>
        </div>
        <div className="flex flex-col gap-1 mt-4">
          <div>
            Last build status: <span className="text-green-500">Success</span>
          </div>
          <div>
            Last built at: <span className="">01.01.2023 14:42</span>
          </div>
        </div>
      </div>

      <div className="w-full flex justify-end">
        <Link href="/app">
          <Button>Details</Button>
        </Link>
      </div>
    </Paper>
  );
};
